### ISSUE TITLE
java.lang.NullPointerException: Null delta application version

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#121]
This is in the server logs when trying to access a project by anonymous

1. User creates project in Teem
2. Logout
3. Refresh screen

Error trace:

```
Mar 06, 2016 5:33:38 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$WaveAtmosphereService onStateChange
INFO: Resource cancelled by remote client: 9a6d0dc7-1342-4d9d-852d-15f739dc653e / _anonymous_1fad3mb85yt8olex9oqp27srj@local.net
Mar 06, 2016 5:33:39 PM org.swellrt.server.box.servlet.AuthenticationService doGet
INFO: Resuming Authenticated user _anonymous_1fad3mb85yt8olex9oqp27srj@local.net
Mar 06, 2016 5:33:39 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$Connection message
INFO: Detected new remote client connection. Cleaning up RPCs
Mar 06, 2016 5:33:39 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$Connection message
INFO: Protocol authenticated as _anonymous_1fad3mb85yt8olex9oqp27srj@local.net
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.frontend.ClientFrontendImpl openRequest
INFO: received openRequest from _anonymous_1fad3mb85yt8olex9oqp27srj@local.net for [WaveId local.net/s+neL3-2MM0oA], filter IdFilter[prefixes=[swl, conv, user+_anonymous_1fad3mb85yt8olex9oqp27srj@local.net]], known wavelets: []
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.frontend.ClientFrontendImpl openRequest
INFO: Subscribed _anonymous_1fad3mb85yt8olex9oqp27srj@local.net to [WaveId local.net/s+neL3-2MM0oA] channel ch166
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.frontend.ClientFrontendImpl openRequest
INFO: snapshot in response is: true
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.frontend.ClientFrontendImpl openRequest
INFO: sending marker for [WaveletName local.net/s+neL3-2MM0oA/local.net/dummy+root]
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.frontend.WaveViewSubscription submitRequest
INFO: Submit oustandinding on channel ch166
Mar 06, 2016 5:33:40 PM org.waveprotocol.box.server.waveserver.WaveServerImpl submitDelta
INFO: Submit to [WaveletName local.net/s+neL3-2MM0oA/local.net/swl+root] by _anonymous_1fad3mb85yt8olex9oqp27srj@local.net @ 0 with 1 ops
java.lang.NullPointerException: Null delta application version
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:209)
        at org.waveprotocol.box.server.frontend.WaveViewSubscription.submitResponse(WaveViewSubscription.java:141)
        at org.waveprotocol.box.server.frontend.UserManager.submitResponse(UserManager.java:136)
        at org.waveprotocol.box.server.frontend.ClientFrontendImpl$1.onFailure(ClientFrontendImpl.java:208)
        at org.waveprotocol.box.server.waveserver.WaveServerImpl$3.onFailure(WaveServerImpl.java:372)
        at org.waveprotocol.box.server.waveserver.WaveServerImpl.submitDelta(WaveServerImpl.java:553)
        at org.waveprotocol.box.server.waveserver.WaveServerImpl.submitRequest(WaveServerImpl.java:369)
        at org.waveprotocol.box.server.frontend.ClientFrontendImpl.submitRequest(ClientFrontendImpl.java:195)
        at org.waveprotocol.box.server.frontend.WaveClientRpcImpl.submit(WaveClientRpcImpl.java:166)
        at org.waveprotocol.box.common.comms.WaveClientRpc$ProtocolWaveClientRpc$1.submit(WaveClientRpc.java:11213)
        at org.waveprotocol.box.common.comms.WaveClientRpc$ProtocolWaveClientRpc.callMethod(WaveClientRpc.java:11352)
        at org.waveprotocol.box.server.rpc.ServerRpcControllerImpl.run(ServerRpcControllerImpl.java:202)
        at org.waveprotocol.box.server.executor.RequestScopeExecutor$1.run(RequestScopeExecutor.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by pablojan** [comment]
I would need more info about 3) What is happening after refresh? does the user open the project already created?

**Comment by atd** [comment]
Yes, teem is in that project's url, so it tries to open it

**Comment by pablojan** [comment]
Unable to reproduce in my SwellRT local sandbox. I could check it on teem directly.
I do following steps (they produce same log)

1) Anonymous login
2) Create wave, write on it, add a participant
3) Logout

[Refresh browser]

4) Resume login (anonymous)
5) Open wave created in step 2)
6) Write on it

**Comment by atd** [comment]
You must create the wave after registering:

1. Register user
2. Log in with user
3. Create wave, write on it
4. Logout

[Refresh browser]
5. Resume login (anonymous)
6. Open wave created in 3

**Comment by atd** [comment]
You can reproduce it in Teem, in branch `redisign`

1. Create community
2. Create teem
3. Logout
4. Refresh

**Comment by pablojan** [comment]
Not a bug
