### ISSUE TITLE
Unable to run swellrt in docker

### ISSUE THREAD

**Issue by MercusChan** [P2Pvalue/swellrt#229]
I run with these commands

> docker run -p 172.17.0.1:27017:27017 --name mongo -d mongo
> docker run -e MONGODB_HOST=172.17.0.1 -e MONGODB_PORT=27017 -e MONGODB_DB=swellrt -p 9898:9898 -h swellrt --name swellrt -d p2pvalue/swellrt

after 30sec, container of swellrt is stopped.

This is the log.

> Jan 09, 2018 9:55:37 AM org.waveprotocol.box.server.persistence.mongodb.MongoDbProvider start
INFO: Started MongoDb persistence
Jan 09, 2018 9:55:37 AM org.waveprotocol.box.server.persistence.mongodb.MongoDbDeltaStore checkDeltasCollectionIndexes
INFO: Ensure MongoDB indexes for 'deltas' collection on 'waveid', 'waveletid' and 'transformed.resultingversion' fields
Jan 09, 2018 9:56:07 AM com.google.inject.internal.MessageProcessor visit
INFO: An exception was caught and reported. Message: com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.17.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting for a server that matches WritableServerSelector. Client view of cluster state is {type=UNKNOWN, servers=[{address=172.17.0.1:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.SocketTimeoutException: connect timed out}}]
	at com.mongodb.connection.BaseCluster.createTimeoutException(BaseCluster.java:369)
	at com.mongodb.connection.BaseCluster.selectServer(BaseCluster.java:101)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:75)
	at com.mongodb.binding.ClusterBinding$ClusterBindingConnectionSource.<init>(ClusterBinding.java:71)
	at com.mongodb.binding.ClusterBinding.getWriteConnectionSource(ClusterBinding.java:68)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:219)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:111)
	at com.mongodb.operation.CreateIndexesOperation.execute(CreateIndexesOperation.java:66)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:458)
	at com.mongodb.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:429)
	at com.mongodb.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:424)
	at org.waveprotocol.box.server.persistence.mongodb.MongoDbDeltaStore.checkDeltasCollectionIndexes(MongoDbDeltaStore.java:87)
	at org.waveprotocol.box.server.persistence.mongodb.MongoDbDeltaStore.create(MongoDbDeltaStore.java:73)
	at org.waveprotocol.box.server.persistence.mongodb.MongoDbProvider.provideMongoDbDeltaStore(MongoDbProvider.java:159)
	at org.waveprotocol.box.server.persistence.PersistenceModule.bindDeltaStore(PersistenceModule.java:157)
	at org.waveprotocol.box.server.persistence.PersistenceModule.configure(PersistenceModule.java:100)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:232)
	at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:236)
	at org.waveprotocol.box.server.ServerMain.run(ServerMain.java:126)
	at org.waveprotocol.box.server.ServerMain.main(ServerMain.java:98)
> 
> Jan 09, 2018 9:56:07 AM org.waveprotocol.box.server.shutdown.ShutdownManager run
> INFO: Shutdown hook is fired.
> Jan 09, 2018 9:56:07 AM org.waveprotocol.box.server.shutdown.ShutdownManager shutdown
> INFO: Start of shutdown procedure.
> Jan 09, 2018 9:56:07 AM org.waveprotocol.box.server.shutdown.ShutdownManager shutdown
> INFO: Shutdown priority class Task
> Jan 09, 2018 9:56:07 AM org.waveprotocol.box.server.shutdown.ShutdownManager shutdown
> INFO: Shutdown of WaveletLoadExecutor ...

Any advices are welcome.

**Comment by MercusChan** [comment]
Sorry, I have confirmed this is problem on running in container.
This is works by setup with these commands

> docker run --name swellrt-mongo -d mongo
> docker run --link swellrt-mongo:swellrt-mongo -e MONGODB_HOST=swellrt-mongo -e MONGODB_PORT=27017 -e MONGODB_DB=swellrt -p 9898:9898 -v /var/log/swellrt:/var/log/swellrt -h swellrt --name swellrt -d p2pvalue/swellrt
