### ISSUE TITLE
TypeError: b.getDelegate is not a function

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#29]
When trying to post to the pad, I get this error:

```
"TypeError: b.getDelegate is not a function
    at Object.f.edit (swellrt-0.js:3495:95)
    at Array.<anonymous> (http://192.168.1.112:8000/js/app.min.js:14:8248)
    at Object.<anonymous> (http://192.168.1.112:8000/js/app.min.js:8:9700)
    at f.$get.f.$digest (http://192.168.1.112:8000/js/app.min.js:6:4045)
    at f.$get.f.$apply (http://192.168.1.112:8000/js/app.min.js:6:5766)
    at es.$$debounceViewValueCommit (http://192.168.1.112:8000/js/app.min.js:8:9477)
    at es.$setViewValue (http://192.168.1.112:8000/js/app.min.js:8:9203)
    at HTMLTextAreaElement.l (http://192.168.1.112:8000/js/app.min.js:6:21811)
    at HTMLTextAreaElement.Z.event.dispatch (http://192.168.1.112:8000/js/app.min.js:2:15875)
    at HTMLTextAreaElement.Z.event.add.v.handle (http://192.168.1.112:8000/js/app.min.js:2:12650)"
```

**Comment by atfornes** [comment]
I had the same problem. It does not occur with revision efec826

Apparently the connexion client ->server works but the server->client connection seems to have issues

**Comment by pablojan** [comment]
@atfornes please could you send me back what SwellRT operations are involved everytime you add a character into the collaborative string object?

Log traces are not enough to debug. Thank you

**Comment by atfornes** [comment]
It was a forgotten RichText editor trying to edit a string value, solved in pear2pear by https://github.com/P2Pvalue/pear2pear/commit/a97ac65080d11623f9a2fc1e4d9a02f353f5075e
