### ISSUE TITLE
Changes to waves are not shown in SwellRT.query

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#92]
After changing data in waves, those changes do not show up in read only queries

**Comment by pablojan** [comment]
Please, provide steps to reproduce within the teem app. Thank you.

**Comment by atd** [comment]
Sure! 


git clone teem 
git checkout directives-refactor
gulp

Create project 

Changes to lastAccess property in project object are only shown within the project view, but not in community's project list

**Comment by pablojan** [comment]
Thank you

**Comment by pablojan** [comment]
I cannot reproduce it.

Changes in waves are being indexed and returned by the search service normally.

The index process is not synchronous. In a server's high-load period, indexing can take more time as it's expected.

**Comment by atd** [comment]
I don't think it is due to a high-load period. My database is empty and there are not barely any other process in the machine

**Comment by atd** [comment]
Did you follow the steps to reproduce it?

It happens to me in several cases. Now I joined a project and in the project list I am not between project participants.

Again, I have not any load in my machine

**Comment by pablojan** [comment]
I couldn't reproduce the general statement of the issue "After changing data in waves, those changes do not show up in read only queries".

I suggest to check the angular-swellrt & teem logics first in order to to provide a list of SwellRT functions invoked. 

At least I would need more info regarding the structure of the wavelet used (e.g. it's a map->list->map->string)

If you are running swellrt in a local environment, please check you are using a mongodb instance as storage. This is mandatory for indexing service.

**Comment by pablojan** [comment]
Sorry I will try teem, locally, later today, now I don't have time.

**Comment by atd** [comment]
Maybe this is related with the problem:

```
WARNING: Error indexing data model [WaveletName local.net/s+69u8NJWSYQD/local.net/swl+root]
java.lang.IllegalArgumentException: fields stored in the db can't have . in them. (Bad Key: 'test@local.net')
        at com.mongodb.DBCollection.validateKey(DBCollection.java:1448)
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1410)
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
        at com.mongodb.DBCollection._checkValue(DBCollection.java:1433)
        at com.mongodb.DBCollection._checkKeys(DBCollection.java:1411)
        at com.mongodb.DBCollection._checkObject(DBCollection.java:1397)
        at com.mongodb.DBApiLayer$MyCollection.update(DBApiLayer.java:318)
        at com.mongodb.DBCollection.update(DBCollection.java:178)
        at com.mongodb.DBCollection.update(DBCollection.java:209)
        at org.swellrt.server.box.index.ModelIndexerDispatcherImpl.storeDataModel(ModelIndexerDispatcherImpl.java:177)
        at org.swellrt.server.box.index.ModelIndexerDispatcherImpl.index(ModelIndexerDispatcherImpl.java:154)
        at org.swellrt.server.box.index.ModelIndexerDispatcherImpl.waveletCommitted(ModelIndexerDispatcherImpl.java:127)
        at org.waveprotocol.box.server.waveserver.WaveletNotificationDispatcher.waveletCommitted(WaveletNotificationDispatcher.java:152)
        at org.waveprotocol.box.server.waveserver.WaveletContainerImpl.notifyOfCommit(WaveletContainerImpl.java:191)
        at org.waveprotocol.box.server.waveserver.WaveletContainerImpl$2.run(WaveletContainerImpl.java:254)
        at org.waveprotocol.box.server.executor.RequestScopeExecutor$1.run(RequestScopeExecutor.java:69)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by pablojan** [comment]
That exception is caused by a not recommended use of SwellRT. The app is using a map key with a dot (".") (e.g. map["local.net"]). This prevents the wavelet to be indexed as long as MongoDB doesn't allow field names having dots. Of course, this could be the reason of this issue

**Comment by pablojan** [comment]
I have reproduced the issue in my local Teem instance. It seems the workspace's wavelet is not being indexed due to the previously commented issue with keys including dots.

```
Advertencia: Error indexing data model [WaveletName local.net/s+j157TzjzX8A/local.net/swl+root]
     [java] java.lang.IllegalArgumentException: fields stored in the db can't have . in them. (Bad Key: 'pablojan@local.net')
     [java] 	at com.mongodb.DBCollection.validateKey(DBCollection.java:1448)
```

![captura de pantalla de 2016-01-04 18 01 14](https://cloud.githubusercontent.com/assets/4454927/12095167/363a920a-b30d-11e5-9f7a-dc5615bfe213.png)

Is lastAccess map trying to use the username as key ('pablojan@local.net' in the screenshot)?

Please check with @atfornes a workaround for it. Since there are simple alternatives to use a key without dots I am not going to consider this as a SwellRT issue.

**Comment by atd** [comment]
Ok, we can look for a workaround. However, let me say that, as developer, a technology with such a limitation looks crappy
