### ISSUE TITLE
Session does not work inside iframe

### ISSUE THREAD

**Issue by atd** [P2Pvalue/swellrt#97]
After embeding Teem in a iframe, session does not start. However, it is working in normal full page access.

Server reports:

```
Jan 05, 2016 6:02:45 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$WaveAtmosphereService onStateChange
INFO: Resource cancelled by remote client: eff9535a-8a13-40b0-a424-d5b8a15b8b49 / _anonymous_13fj013ye4s801ucqlkr5dxcqm@local.net
Jan 05, 2016 6:02:46 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$2 sessionCreated
INFO: Session created: 1mzbxv3y6wfxd15e62cm6xioat
Jan 05, 2016 6:02:46 PM org.waveprotocol.box.server.rpc.AuthenticationServlet doPost
INFO: Authenticated user _anonymous_1mzbxv3y6wfxd15e62cm6xioat@local.net
Jan 05, 2016 6:02:46 PM org.waveprotocol.box.server.rpc.ServerRpcProvider$WaveAtmosphereService onRequest
INFO: Exception on channel.
java.lang.IllegalArgumentException: Protocol user doesn't match session user
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:93)
        at org.waveprotocol.box.server.rpc.ServerRpcProvider$Connection.message(ServerRpcProvider.java:324)
        at org.waveprotocol.box.server.rpc.WebSocketChannel.handleMessageString(WebSocketChannel.java:122)
        at org.waveprotocol.box.server.rpc.atmosphere.AtmosphereChannel.onMessage(AtmosphereChannel.java:80)
        at org.waveprotocol.box.server.rpc.ServerRpcProvider$WaveAtmosphereService.onRequest(ServerRpcProvider.java:898)
        at org.atmosphere.cpr.AsynchronousProcessor.action(AsynchronousProcessor.java:174)
        at org.atmosphere.cpr.AsynchronousProcessor.suspended(AsynchronousProcessor.java:95)
        at org.atmosphere.container.Jetty9AsyncSupportWithWebSocket.service(Jetty9AsyncSupportWithWebSocket.java:179)
        at org.atmosphere.cpr.AtmosphereFramework.doCometSupport(AtmosphereFramework.java:1782)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:421)
        at org.atmosphere.websocket.DefaultWebSocketProcessor$2.run(DefaultWebSocketProcessor.java:274)
        at org.atmosphere.util.VoidExecutorService.execute(VoidExecutorService.java:101)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.dispatch(DefaultWebSocketProcessor.java:269)
        at org.atmosphere.websocket.DefaultWebSocketProcessor.invokeWebSocketProtocol(DefaultWebSocketProcessor.java:292)
        at org.atmosphere.container.Jetty9WebSocketHandler.onWebSocketText(Jetty9WebSocketHandler.java:77)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextMessage(JettyListenerEventDriver.java:127)
        at org.eclipse.jetty.websocket.common.message.SimpleTextMessage.messageComplete(SimpleTextMessage.java:69)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.appendMessage(AbstractEventDriver.java:64)
        at org.eclipse.jetty.websocket.common.events.JettyListenerEventDriver.onTextFrame(JettyListenerEventDriver.java:121)
        at org.eclipse.jetty.websocket.common.events.AbstractEventDriver.incomingFrame(AbstractEventDriver.java:169)
        at org.eclipse.jetty.websocket.common.WebSocketSession.incomingFrame(WebSocketSession.java:302)
        at org.eclipse.jetty.websocket.common.extensions.ExtensionStack.incomingFrame(ExtensionStack.java:204)
        at org.eclipse.jetty.websocket.common.Parser.notifyFrame(Parser.java:223)
        at org.eclipse.jetty.websocket.common.Parser.parse(Parser.java:260)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.read(AbstractWebSocketConnection.java:500)
        at org.eclipse.jetty.websocket.common.io.AbstractWebSocketConnection.onFillable(AbstractWebSocketConnection.java:409)
        at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)
        at java.lang.Thread.run(Thread.java:745)


```

**Comment by atd** [comment]
I am afraid this is related with third-party cookies
